version: 1.0.1
services:

  shop-clothes_database:
    container_name: shop-clothes_database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: demo_shop_clothes
    ports:
      - 3308:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - shop-clothes_network
    restart: always

  shop-clothes_redis:
    container_name: shop-clothes_redis
    image: redis
    ports:
      - 6378:6379
    volumes:
      - redis-data:/data
    networks:
      - shop-clothes_network
    restart: always

  backend:
    container_name: shop-clothes_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8888:8080
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shop-clothes_database:3306/demo_shop_clothes?createDatabaseIfNotExist=true
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - backend:/file:/file
    networks:
      - shop-clothes_network
    depends_on:
      - shop-clothes_database
      - shop-clothes_redis
    restart: always

volumes:
  database:
  backend:
  redis-data:
networks:
  shop-clothes_network:
    name: shop-clothes_network
    driver: bridge